version: '3'

services:
  jekyll:
    image: jekyll/jekyll:latest
    volumes:
      - "$PWD:/srv/jekyll"
      - "$PWD/vendor/bundle:/usr/local/bundle"
    command: jekyll serve
    restart: always
    networks:
      - default
      - webnet
    environment:
      JEKYLL_ENV: production
      VIRTUAL_HOST: blog.davidmaxson.name
      VIRTUAL_PORT: 4000
      LETSENCRYPT_HOST: blog.davidmaxson.name
      LETSENCRYPT_EMAIL: scnerd@gmail.com


networks:
  webnet:
    external:
      name: webnet
